"""foreign ids

Revision ID: 40c6013a55fd
Revises: e747d50edcd3
Create Date: 2024-12-02 13:20:46.146061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c6013a55fd'
down_revision = 'e747d50edcd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('traveler_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('localexpert_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('advertiser_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_posts_advertiser_id_advertisers'), 'advertisers', ['advertiser_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_posts_traveler_id_travelers'), 'travelers', ['traveler_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_posts_localexpert_id_localexperts'), 'localexperts', ['localexpert_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_localexpert_id_localexperts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_posts_traveler_id_travelers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_posts_advertiser_id_advertisers'), type_='foreignkey')
        batch_op.drop_column('advertiser_id')
        batch_op.drop_column('localexpert_id')
        batch_op.drop_column('traveler_id')

    # ### end Alembic commands ###
