"""Post class addition

Revision ID: 55665a0fcca6
Revises: 1cb7342ee1e0
Create Date: 2024-11-29 19:56:13.366273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55665a0fcca6'
down_revision = '1cb7342ee1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('hashtag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_post',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['posts.id'], name=op.f('fk_activity_post_activity_id_posts')),
    sa.ForeignKeyConstraint(['post_id'], ['activities.id'], name=op.f('fk_activity_post_post_id_activities')),
    sa.PrimaryKeyConstraint('activity_id', 'post_id')
    )
    op.create_table('advertiser_localexpert',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['localexperts.id'], name=op.f('fk_advertiser_localexpert_advertiser_id_localexperts')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['advertisers.id'], name=op.f('fk_advertiser_localexpert_localexpert_id_advertisers')),
    sa.PrimaryKeyConstraint('advertiser_id', 'localexpert_id')
    )
    op.create_table('advertiser_post',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['posts.id'], name=op.f('fk_advertiser_post_advertiser_id_posts')),
    sa.ForeignKeyConstraint(['post_id'], ['advertisers.id'], name=op.f('fk_advertiser_post_post_id_advertisers')),
    sa.PrimaryKeyConstraint('advertiser_id', 'post_id')
    )
    op.create_table('island_post',
    sa.Column('island_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['island_id'], ['posts.id'], name=op.f('fk_island_post_island_id_posts')),
    sa.ForeignKeyConstraint(['post_id'], ['islands.id'], name=op.f('fk_island_post_post_id_islands')),
    sa.PrimaryKeyConstraint('island_id', 'post_id')
    )
    op.create_table('localexpert_post',
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['localexpert_id'], ['posts.id'], name=op.f('fk_localexpert_post_localexpert_id_posts')),
    sa.ForeignKeyConstraint(['post_id'], ['localexperts.id'], name=op.f('fk_localexpert_post_post_id_localexperts')),
    sa.PrimaryKeyConstraint('localexpert_id', 'post_id')
    )
    op.create_table('traveler_post',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_traveler_post_post_id_posts')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_post_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traveler_post')
    op.drop_table('localexpert_post')
    op.drop_table('island_post')
    op.drop_table('advertiser_post')
    op.drop_table('advertiser_localexpert')
    op.drop_table('activity_post')
    op.drop_table('posts')
    # ### end Alembic commands ###
