"""Hashtag class creation

Revision ID: 7597bfefc389
Revises: 7976594f61bd
Create Date: 2024-12-05 17:01:16.813551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7597bfefc389'
down_revision = '7976594f61bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('advertiser_hashtag',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_advertiser_hashtag_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], name=op.f('fk_advertiser_hashtag_hashtag_id_hashtags')),
    sa.PrimaryKeyConstraint('advertiser_id', 'hashtag_id')
    )
    op.create_table('localexpert_hashtag',
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], name=op.f('fk_localexpert_hashtag_hashtag_id_hashtags')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_localexpert_hashtag_localexpert_id_localexperts')),
    sa.PrimaryKeyConstraint('localexpert_id', 'hashtag_id')
    )
    op.create_table('traveler_hashtag',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], name=op.f('fk_traveler_hashtag_hashtag_id_hashtags')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_hashtag_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'hashtag_id')
    )
    op.create_table('post_hashtag',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], name=op.f('fk_post_hashtag_hashtag_id_hashtags')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_hashtag_post_id_posts')),
    sa.PrimaryKeyConstraint('post_id', 'hashtag_id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('hashtag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashtag', sa.VARCHAR(), nullable=True))

    op.drop_table('post_hashtag')
    op.drop_table('traveler_hashtag')
    op.drop_table('localexpert_hashtag')
    op.drop_table('advertiser_hashtag')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
