"""fixing database schema

Revision ID: 7976594f61bd
Revises: b6000a14e499
Create Date: 2024-12-05 16:48:50.576917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7976594f61bd'
down_revision = 'b6000a14e499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=True),
    sa.Column('body', sa.VARCHAR(), nullable=True),
    sa.Column('hashtag', sa.VARCHAR(), nullable=True),
    sa.Column('traveler_id', sa.INTEGER(), nullable=False),
    sa.Column('localexpert_id', sa.INTEGER(), nullable=False),
    sa.Column('advertiser_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name='fk_posts_advertiser_id_advertisers'),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name='fk_posts_localexpert_id_localexperts'),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name='fk_posts_traveler_id_travelers'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
