"""changing comment column to be relationship

Revision ID: 891cdcffd19a
Revises: 22f71e3f0337
Create Date: 2024-12-18 10:26:25.896374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '891cdcffd19a'
down_revision = '22f71e3f0337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
