"""Adding validation schema to new psot

Revision ID: 9e512e3c4d7c
Revises: 891cdcffd19a
Create Date: 2024-12-19 19:04:44.877345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e512e3c4d7c'
down_revision = '891cdcffd19a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
