"""notes addition to local expert model

Revision ID: b3f3bc3cbebc
Revises: 9d22b6d820ea
Create Date: 2024-11-25 18:37:38.797250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f3bc3cbebc'
down_revision = '9d22b6d820ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('localexperts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('localexperts', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
