"""comments class

Revision ID: d60fd2eb8f9f
Revises: 15781fad18ac
Create Date: 2024-12-07 13:45:44.713748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60fd2eb8f9f'
down_revision = '15781fad18ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.Column('localexpert_id', sa.Integer(), nullable=True),
    sa.Column('advertiser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_comments_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_comments_localexpert_id_localexperts')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_comments_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertiser_comment',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_advertiser_comment_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_advertiser_comment_comment_id_comments')),
    sa.PrimaryKeyConstraint('advertiser_id', 'comment_id')
    )
    op.create_table('localexpert_comment',
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_localexpert_comment_comment_id_comments')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_localexpert_comment_localexpert_id_localexperts')),
    sa.PrimaryKeyConstraint('localexpert_id', 'comment_id')
    )
    op.create_table('post_comment',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_post_comment_comment_id_comments')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_comment_post_id_posts')),
    sa.PrimaryKeyConstraint('post_id', 'comment_id')
    )
    op.create_table('traveler_comment',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_traveler_comment_comment_id_comments')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_comment_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traveler_comment')
    op.drop_table('post_comment')
    op.drop_table('localexpert_comment')
    op.drop_table('advertiser_comment')
    op.drop_table('comments')
    # ### end Alembic commands ###
