"""Database initialization

Revision ID: e10f3a39b54c
Revises: 
Create Date: 2024-12-07 20:47:17.457061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10f3a39b54c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localexperts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('travelers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('advertiser_hashtag',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_advertiser_hashtag_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], name=op.f('fk_advertiser_hashtag_hashtag_id_hashtags')),
    sa.PrimaryKeyConstraint('advertiser_id', 'hashtag_id')
    )
    op.create_table('advertiser_localexpert',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_advertiser_localexpert_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_advertiser_localexpert_localexpert_id_localexperts')),
    sa.PrimaryKeyConstraint('advertiser_id', 'localexpert_id')
    )
    op.create_table('localexpert_hashtag',
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], name=op.f('fk_localexpert_hashtag_hashtag_id_hashtags')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_localexpert_hashtag_localexpert_id_localexperts')),
    sa.PrimaryKeyConstraint('localexpert_id', 'hashtag_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.Column('localexpert_id', sa.Integer(), nullable=True),
    sa.Column('advertiser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_posts_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_posts_localexpert_id_localexperts')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_posts_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traveler_advertiser',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_traveler_advertiser_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_advertiser_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'advertiser_id')
    )
    op.create_table('traveler_hashtag',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], name=op.f('fk_traveler_hashtag_hashtag_id_hashtags')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_hashtag_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'hashtag_id')
    )
    op.create_table('traveler_localexpert',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_traveler_localexpert_localexpert_id_localexperts')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_localexpert_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'localexpert_id')
    )
    op.create_table('advertiser_post',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_advertiser_post_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_advertiser_post_post_id_posts')),
    sa.PrimaryKeyConstraint('advertiser_id', 'post_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.Column('localexpert_id', sa.Integer(), nullable=True),
    sa.Column('advertiser_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_comments_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_comments_localexpert_id_localexperts')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_comments_post_id_posts')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_comments_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localexpert_post',
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_localexpert_post_localexpert_id_localexperts')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_localexpert_post_post_id_posts')),
    sa.PrimaryKeyConstraint('localexpert_id', 'post_id')
    )
    op.create_table('post_hashtag',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], name=op.f('fk_post_hashtag_hashtag_id_hashtags')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_hashtag_post_id_posts')),
    sa.PrimaryKeyConstraint('post_id', 'hashtag_id')
    )
    op.create_table('traveler_post',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_traveler_post_post_id_posts')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_post_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'post_id')
    )
    op.create_table('advertiser_comment',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_advertiser_comment_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_advertiser_comment_comment_id_comments')),
    sa.PrimaryKeyConstraint('advertiser_id', 'comment_id')
    )
    op.create_table('localexpert_comment',
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_localexpert_comment_comment_id_comments')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_localexpert_comment_localexpert_id_localexperts')),
    sa.PrimaryKeyConstraint('localexpert_id', 'comment_id')
    )
    op.create_table('traveler_comment',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_traveler_comment_comment_id_comments')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_comment_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traveler_comment')
    op.drop_table('localexpert_comment')
    op.drop_table('advertiser_comment')
    op.drop_table('traveler_post')
    op.drop_table('post_hashtag')
    op.drop_table('localexpert_post')
    op.drop_table('comments')
    op.drop_table('advertiser_post')
    op.drop_table('traveler_localexpert')
    op.drop_table('traveler_hashtag')
    op.drop_table('traveler_advertiser')
    op.drop_table('posts')
    op.drop_table('localexpert_hashtag')
    op.drop_table('advertiser_localexpert')
    op.drop_table('advertiser_hashtag')
    op.drop_table('travelers')
    op.drop_table('localexperts')
    op.drop_table('hashtags')
    op.drop_table('advertisers')
    # ### end Alembic commands ###
