"""Recreation of databases

Revision ID: ea2bbf40e3f9
Revises: 
Create Date: 2024-12-04 18:58:13.128977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2bbf40e3f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('islands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localexperts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('travelers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('advertiser_activity',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_advertiser_activity_activity_id_activities')),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_advertiser_activity_advertiser_id_advertisers')),
    sa.PrimaryKeyConstraint('advertiser_id', 'activity_id')
    )
    op.create_table('advertiser_island',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('island_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_advertiser_island_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['island_id'], ['islands.id'], name=op.f('fk_advertiser_island_island_id_islands')),
    sa.PrimaryKeyConstraint('advertiser_id', 'island_id')
    )
    op.create_table('advertiser_localexpert',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_advertiser_localexpert_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_advertiser_localexpert_localexpert_id_localexperts')),
    sa.PrimaryKeyConstraint('advertiser_id', 'localexpert_id')
    )
    op.create_table('island_activity',
    sa.Column('island_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_island_activity_activity_id_activities')),
    sa.ForeignKeyConstraint(['island_id'], ['islands.id'], name=op.f('fk_island_activity_island_id_islands')),
    sa.PrimaryKeyConstraint('island_id', 'activity_id')
    )
    op.create_table('localexpert_activity',
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_localexpert_activity_activity_id_activities')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_localexpert_activity_localexpert_id_localexperts')),
    sa.PrimaryKeyConstraint('localexpert_id', 'activity_id')
    )
    op.create_table('localexpert_island',
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.Column('island_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['island_id'], ['islands.id'], name=op.f('fk_localexpert_island_island_id_islands')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_localexpert_island_localexpert_id_localexperts')),
    sa.PrimaryKeyConstraint('localexpert_id', 'island_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('hashtag', sa.String(), nullable=True),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.Column('localexpert_id', sa.Integer(), nullable=True),
    sa.Column('advertiser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_posts_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_posts_localexpert_id_localexperts')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_posts_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traveler_activity',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_traveler_activity_activity_id_activities')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_activity_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'activity_id')
    )
    op.create_table('traveler_advertiser',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_traveler_advertiser_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_advertiser_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'advertiser_id')
    )
    op.create_table('traveler_island',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('island_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['island_id'], ['islands.id'], name=op.f('fk_traveler_island_island_id_islands')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_island_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'island_id')
    )
    op.create_table('traveler_localexpert',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_traveler_localexpert_localexpert_id_localexperts')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_localexpert_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'localexpert_id')
    )
    op.create_table('activity_post',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_post_activity_id_activities')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_activity_post_post_id_posts')),
    sa.PrimaryKeyConstraint('activity_id', 'post_id')
    )
    op.create_table('advertiser_post',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], name=op.f('fk_advertiser_post_advertiser_id_advertisers')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_advertiser_post_post_id_posts')),
    sa.PrimaryKeyConstraint('advertiser_id', 'post_id')
    )
    op.create_table('island_post',
    sa.Column('island_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['island_id'], ['islands.id'], name=op.f('fk_island_post_island_id_islands')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_island_post_post_id_posts')),
    sa.PrimaryKeyConstraint('island_id', 'post_id')
    )
    op.create_table('localexpert_post',
    sa.Column('localexpert_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['localexpert_id'], ['localexperts.id'], name=op.f('fk_localexpert_post_localexpert_id_localexperts')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_localexpert_post_post_id_posts')),
    sa.PrimaryKeyConstraint('localexpert_id', 'post_id')
    )
    op.create_table('traveler_post',
    sa.Column('traveler_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_traveler_post_post_id_posts')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.id'], name=op.f('fk_traveler_post_traveler_id_travelers')),
    sa.PrimaryKeyConstraint('traveler_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traveler_post')
    op.drop_table('localexpert_post')
    op.drop_table('island_post')
    op.drop_table('advertiser_post')
    op.drop_table('activity_post')
    op.drop_table('traveler_localexpert')
    op.drop_table('traveler_island')
    op.drop_table('traveler_advertiser')
    op.drop_table('traveler_activity')
    op.drop_table('posts')
    op.drop_table('localexpert_island')
    op.drop_table('localexpert_activity')
    op.drop_table('island_activity')
    op.drop_table('advertiser_localexpert')
    op.drop_table('advertiser_island')
    op.drop_table('advertiser_activity')
    op.drop_table('travelers')
    op.drop_table('localexperts')
    op.drop_table('islands')
    op.drop_table('advertisers')
    op.drop_table('activities')
    # ### end Alembic commands ###
